Speed up multigrid NDT align
tier4/ndt_omp pull request #41
Opened 2024-03-14 02:00 UTC by anhnv3991

- Speed up multigrid NDT align by removing duplicated processing and replace deep copy by reference

2024-03-14 09:50 UTC, SakodaShintaro reviewed
It seems to be steadily speeding up. Thank you very much.

![elapsed_milliseconds](https://github.com/tier4/ndt_omp/assets/28504069/30d2f86e-7435-4e6a-9273-2edeae15f0f7)

Since the speed has improved, I also updated result.csv.

2024-03-14 09:50 UTC, SakodaShintaro commented on include/multigrid_pclomp/multigrid_ndt_omp_impl.hpp
> +    double tmp_score = 0;
Is this variable used correctly?

2024-03-15 09:24 UTC, anhnv3991 commented on include/multigrid_pclomp/multigrid_ndt_omp_impl.hpp
> +    double tmp_score = 0;
@SakodaShintaro I fixed it.

2024-03-15 09:43 UTC, SakodaShintaro approved these changes
Looks Good To Me!

2024-03-15 09:58 UTC, SakodaShintaro requested changes
Sorry, I'd like to check it out a little more, so please let me withdraw my approval.

2024-03-15 10:32 UTC, SakodaShintaro approved these changes
I carefully checked the operation. It's OK!

2024-03-15 10:36 UTC, merged